services:
  api:
    build:
      context: .
      target: dev # usa o stage "dev"
    container_name: extrai-bff
    env_file: .env.dev
    environment:
      PYTHONPATH: /app
      APP_PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    profiles: ["dev"]

  api-prod:
    build:
      context: .
      target: prod
    container_name: extrai-bff-prod
    env_file: .env.prod
    environment:
      PYTHONPATH: /app
      APP_PORT: 8000
    ports:
      - "8001:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    profiles: ["prod"]
