services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extrai-bff
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src # hot-reload em dev
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
