openapi: 3.0.3
info:
  title: Extrai BFF API
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health
      responses:
        "200": { description: OK }
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
components:
  schemas:
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email: { type: string, format: email }
        password: { type: string }
    LoginResponse:
      type: object
      properties:
        access_token: { type: string }
        token_type: { type: string, default: bearer }