name: cd-vps
on:
  push:
    tags: ["v*.*.*"] # deploy só quando criar tag vX.Y.Z

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare image tag
        id: prep
        run: |
          TAG=${GITHUB_REF_NAME#v}
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: SSH deploy (pull & restart)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            set -e
            REGISTRY="${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}"
            REPO="${{ secrets.DOCKER_REPO || github.repository }}"
            IMAGE="$REGISTRY/$REPO:${{ steps.prep.outputs.TAG }}"

            mkdir -p /opt/extrai-bff
            cd /opt/extrai-bff

            # Arquivo compose deve referenciar a imagem $IMAGE (ou usar envsubst)
            echo "Pulling $IMAGE"
            docker pull "$IMAGE"

            # Exporta variáveis e recria serviço
            export IMAGE="$IMAGE"
            docker compose -f compose.yml --env-file .env.prod up -d

            # Healthcheck simples
            sleep 5
            curl -fsS http://localhost:8000/health || (docker compose logs --no-color api && exit 1)

            # (Opcional) Migrações
            # docker compose exec -T api alembic upgrade head
