name: ci
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Lint
        run: |
          python -m pip install ruff || true
          ruff check src tests

      - name: Tests
        env:
          # opcional: variáveis mínimas para testes
          POSTGRES_URL: postgresql+psycopg://user:pass@localhost:5432/extrai
          REDIS_URL: redis://localhost:6379/0
        run: pytest -q

  docker-build:
    needs: lint-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}
          username: ${{ secrets.DOCKER_USERNAME || github.actor }}
          password: ${{ secrets.DOCKER_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Extract meta (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ secrets.DOCKER_REPO || github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build (no push on PR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/Dockerfile.app
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ secrets.DOCKER_REPO || github.repository }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ secrets.DOCKER_REPO || github.repository }}:buildcache,mode=max
